version: '3'

services:

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password

  wordpress:
    image: wp-graphql/wordpress:${WORDPRESS_IMAGE_VERSION:-latest}
    build:
      context: ./docker
    depends_on:
      - mysql
    ports:
      - "8080:80"
    volumes:
      - ./local/public:/var/www/html # WP core files.
      - .:/var/www/html/wp-content/plugins/wp-graphql-testcase
      - ./docker/wp-config.php:/var/www/html/wp-config.php
    environment:
      COMPOSER_HOME: /tmp/.composer
      APACHE_RUN_USER: "#1000" # Ensure Apache can write to the filesystem.