name: continuous_integration

on:
  schedule:
    - cron:  '0 4 * * 5'
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - develop

jobs:
  continuous_integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.3', '8.0' ]
        wordpress: [ '5.7.2' ]
    name: Make sure that the WPGraphQLTestCase works!!!
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, mbstring

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Install PHPUnit dependencies
        env:
          PHP_VERSION: ${{ matrix.php }}
          WP_VERSION: ${{ matrix.wordpress }}
        run: |
          composer install --ignore-platform-reqs
          composer require wp-phpunit/wp-phpunit --ignore-platform-reqs

      - name: Run PHPUnit Tests w/ Docker.
        env:
          PHP_VERSION: ${{ matrix.php }}
          WP_VERSION: ${{ matrix.wordpress }}
        run: composer run-phpunit -- -- --coverage-text

      - name: Install Codeception dependencies
        env:
          PHP_VERSION: ${{ matrix.php }}
          WP_VERSION: ${{ matrix.wordpress }}
        run: |
          composer install
          composer require codeception/module-asserts \
            codeception/util-universalframework \
            codeception/module-rest \
            lucatume/wp-browser

      - name: Run Codeception Tests w/ Docker.
        env:
          PHP_VERSION: ${{ matrix.php }}
          WP_VERSION: ${{ matrix.wordpress }}
        run: composer run-codeception -- -- --coverage --coverage-xml

      - name: Push Codecoverage to Coveralls.io
        env:
          COVERALLS_RUN_LOCALLY: 1
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          PHP_VERSION: ${{ matrix.php }}
          WP_VERSION: ${{ matrix.wordpress }}
        run: |
          docker-compose run --rm \
          --workdir=/var/www/html/wp-content/plugins/wp-graphql-testcase \
          --user $(id -u) \
          -e COVERALLS_RUN_LOCALLY=1 -e COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN \
          wordpress \
          vendor/bin/php-coveralls -v
