name: continuous_integration

on:
  schedule:
    - cron:  '0 4 * * 5'
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - develop
    paths:
      - '**.php'

jobs:
  continuous_integration:
    runs-on: ubuntu-latest
    name: Make sure that the WPGraphQLTestCase works!!!
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'
          extensions: json, mbstring

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Install dependencies
        run: |
          composer install --no-autoloader
          composer dumpautoload -o
          composer install

      - name: Run Tests w/ Docker.
        run: composer run-tests -- --coverage --coverage-xml

      - name: Push Codecoverage to Coveralls.io
        env:
          COVERALLS_RUN_LOCALLY: 1
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          docker-compose run --rm \
          --workdir=/var/www/html/wp-content/plugins/wp-graphql-testcase \
          --user $(id -u) \
          -e COVERALLS_RUN_LOCALLY=1 -e COVERALLS_REPO_TOKEN=${{ COVERALLS_REPO_TOKEN }} \
          wordpress \
          vendor/bin/php-coveralls -v
